### ISSUE TITLE
Missing https://www.iis.net/ support

### ISSUE THREAD

**Issue by prisis** [thephpleague/uri#101]
## Issue summary

Missing support for iis

### System informations
| Information | Description |
|--------------|---------|
| League\Uri version | 5.0.0 |
| PHP/HHVM version | php 7 |
| OS Platform | windows |

## Standalone code, or other way to reproduce the problem

```php
$server = [
    'HTTP_HOST'      => 'example.org',
    'IIS_WasUrlRewritten' => '1',
    'UNENCODED_URL' => '/foo/bar',
];
Uri::createFromServer($server);
```
More tests : https://github.com/zendframework/zend-diactoros/blob/master/test/ServerRequestFactoryTest.php#L113

### Expected result
'http://example.org/foo/bar'
### Actual result
'http://example.org'

**Comment by nyamsprod** [comment]
@prisis Indeed I do not take into account IIS server but if you have a PR to add IIS support I will gladly review and merge it to the library

**Comment by nyamsprod** [comment]
@prisis FWIW IIS is supported what is not supported in IIS rewrite. It could be added but for instance because of security issue support for `HTTP_X_REWRITE_URL` or `HTTP_X_ORIGINAL_URL` will never land on the named constructor.

**Comment by nyamsprod** [comment]
version 1.0.5 of uri-schemes has been released with the patch.
