### ISSUE TITLE
URLs with non-ASCII characters are parsed with (partially) empty host

### ISSUE THREAD

**Issue by fluidsonic** [thephpleague/uri#102]
## Issue summary

URLs containing German umlauts or other non-ASCII characters in the host part cause a Uri object to be created but with a (partially) empty host.

### System informations

| Information | Description |
|--------------|---------|
| League\Uri version | 5.0.0 |
| PHP/HHVM version | 7.1.7 |
| OS Platform | macOS 10.12.5 |

## Standalone code, or other way to reproduce the problem

```php
echo HttpUri::createFromString("http://www.beim-mühlenwirt.de") . "\n";
echo HttpUri::createFromString("http://مثال.السعودية") . "\n";
```

### Expected result

```
http://www.beim-mühlenwirt.de
http://مثال.السعودية
```

### Actual result

```
http://www..de
http://.
```

**Comment by nyamsprod** [comment]
@fluidsonic did you use the latest version (ie: made a composer update before ?). On my local machine on PHP7.0 I got the following result:

```php
use League\Uri\Schemes\Http;
var_dump(
    (string) Http::createFromString("http://www.beim-mühlenwirt.de"),
    (string) Http::createFromString("http://مثال.السعودية")
);
string(36) "http://www.xn--beim-mhlenwirt-lsb.de"
string(36) "http://xn--mgbh0fb.xn--mgberp4a5d4ar"
```
Which is normal since URI are converted in RFC3986 format If you need to keep the RFC3987 format you are required to used the Formatter class.

**Comment by fluidsonic** [comment]
@nyamsprod yes, I've installed the package right before I ran into the problem. I've never used it before so nothing is cached.
is it possible that it depends on the locale or on the internal encoding, etc.?

**Comment by nyamsprod** [comment]
No at all the only dependencies are listed on the composer manifest. https://github.com/thephpleague/uri/blob/master/composer.json#L35-L37

**Comment by fluidsonic** [comment]
I don't mind whether it's RFC3986 or RFC3987. For now I just use the parser for validating the URL. I just found that error odd and worth mentioning :)

I was able to isolate the root cause of this bug.

In `uri-scheme`'s [`AbstractUri.php:352`](https://github.com/thephpleague/uri-schemes/blob/master/src/AbstractUri.php#L352) the call to `strtolower` breaks the UTF-8 strings.

Using `mb_strtolower` instead fixes the issue :)

**Comment by nyamsprod** [comment]
@fluidsonic strange because I never got this issue :) ... I'll look into it and fix it.

**Comment by nyamsprod** [comment]
again seeing how it works in all PHP version I still don't see the issue with the highlighted code https://3v4l.org/6BM64

**Comment by fluidsonic** [comment]
It depends on the system locale.

test.php:
```php
<?php echo var_dump(strtolower("مثال.السعودية"));
```

```
$ LC_ALL=en_US.ISO-8859-1 php test.php 
string(25) "مثال.السعودية"

$ LC_ALL=en_US.UTF-8 php test.php 
string(25) "????????.????????????????
```

**Comment by nyamsprod** [comment]
The fix is quite easy ... https://github.com/thephpleague/uri-schemes/commit/3a4fa7a939ad151b345491c7fabd0975ab4e27be 
I'll probably release a patch this week

@fluidsonic thanks for reporting the bug and for providing solid evidence 👍

**Comment by fluidsonic** [comment]
@nyamsprod thanks for the quick response & patch :)

Note that `strtolower` is used once more within the same file. It may make sense to scan the whole project for `strtolower`/`strtoupper` and other usages of string functions which don't properly support multi-byte strings.

**Comment by nyamsprod** [comment]
yes it is used for the scheme part but that's ok because scheme can not contains multibytes characters. This is checked before using `strtolower`. I've checked it before applying the patch

**Comment by nyamsprod** [comment]
- league/uri-components [1.0.5](https://github.com/thephpleague/uri-components/releases/tag/1.0.5)
- league/uri-schemes [1.0.6](https://github.com/thephpleague/uri-schemes/releases/tag/1.0.6)

are released with the patch. a simple 

```
composer update league/uri 
```
should be enough to get the patch version
