### ISSUE TITLE
Support for PHP 7.2 in 4.x branch

### ISSUE THREAD

**Issue by pamil** [thephpleague/uri#105]
Since `INTL_IDNA_VARIANT_2003` variant has been deprecated in PHP 7.2, using Payum which uses League/Uri v4 is impossible on that version (I've listed the details here: https://github.com/Sylius/Sylius/pull/8771#issuecomment-335422273).

The thing I'd like to introduce in `4.2.3` release is to change `idn_to_ascii` and `idn_to_utf8` function calls with something like:

Either:

```php
@idn_to_ascii($part)
```

Or:

```php
if (defined('INTL_IDNA_VARIANT_UTS46')) {
  $part = idn_to_ascii($part, 0, INTL_IDNA_VARIANT_UTS46);
} else {
  $part = idn_to_ascii($part);
}
```

Or:

```php
if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
  $part = @idn_to_ascii($part);
} else {
  $part = idn_to_ascii($part);
}
```

All I need to fix this is the choice of the suitable solution, then merging a PR and releasing `4.2.3`. It really would help anyone using Payum with the most recent PHP version and I'll be grateful for help :)

I've copy-pasted this issue from this package's dependency (https://github.com/jeremykendall/php-domain-parser/issues/204) which the same thing being done.

**Comment by nyamsprod** [comment]
@pamil league URI v4 is EOL I'm afraid your concerned is patch in league v5.

**Comment by nyamsprod** [comment]
@pamil in your patch upgrade the pdp requirement to v4-alpha3 If I'm not mistaken I'll review your patch ASAP

**Comment by pamil** [comment]
@nyamsprod #106 ready for review :)

**Comment by nyamsprod** [comment]
merged released so now it is closed
