### ISSUE TITLE
Impossible to install 5.1.0 because of jeremykendall/php-domain-parser stability

### ISSUE THREAD

**Issue by ruudk** [thephpleague/uri#109]
It seems that version 5.1.0 depends on an Alpha package. This will prevent you from upgrading when you have the default minimum stability settings (stable):

```
  Problem 1
    - Installation request for league/uri ^5.1 -> satisfiable by league/uri[5.1.0].
    - league/uri 5.1.0 requires jeremykendall/php-domain-parser 4.0.3-alpha -> satisfiable by jeremykendall/php-domain-parser[4.0.3-alpha] but these conflict with your requirements or minimum-stability.
```

**Comment by nyamsprod** [comment]
@jeremykendall is the one who can resolve this I'm afraid 😥

**Comment by ruudk** [comment]
Yeah, but the problem is that this stable package depends on alpha packages... that shouldn't have happened I think ;)

**Comment by nyamsprod** [comment]
@ruudk I've created a package that will solve the problem just need to test 2 or 3 things ... but I'll have to bump the version to 5.2 you can check the resolution progress here https://github.com/thephpleague/uri-components/pull/9

**Comment by ruudk** [comment]
@nyamsprod Great, thanks :) I will subscribe to that issue.

**Comment by nyamsprod** [comment]
@ruudk the master is bugfixed.. you can try to download it to see if everything is OK now. If so I'll release version 5.2 with the dependency swap.

**Comment by nyamsprod** [comment]
@ruudk did you get a chance to try the master ?

**Comment by ruudk** [comment]
Sorry, I cannot test it easily :(

**Comment by ruudk** [comment]
Tests are ✅ right :D ?

**Comment by nyamsprod** [comment]
okay no problem ... I'll do a pre-release later today and if all is good i'll make a stable 5.2 release later on

**Comment by nyamsprod** [comment]
@ruudk yes all tests are passing 👍

**Comment by nyamsprod** [comment]
@ruudk just to let you know that all is good I just have one issue to resolve and 5.2 will be released with tones of goodies and PHP7.2 proper support 👍 . I'll close this one are resolve in the mean time if you don't mind

**Comment by ruudk** [comment]
Thanks! :)

**Comment by driesvints** [comment]
@nyamsprod I'd keep this open tbh until a release is tagged which fixes this. It's still an issue atm.

**Comment by driesvints** [comment]
Thanks for taking a look btw!

**Comment by nyamsprod** [comment]
release tag is no its way that's why I've closed it 👍

**Comment by nyamsprod** [comment]
https://github.com/thephpleague/uri/releases/tag/5.2.0
