### ISSUE TITLE
Parse from $_SERVER['HTTP_HOST']

### ISSUE THREAD

**Issue by strarsis** [thephpleague/uri#111]
## Issue summary

It would be a nice addition and helpful if this library can also parse from `$_SERVER['HTTP_HOST']`.
`$_SERVER['HTTP_HOST']` doesn't contain the scheme/protocol ('http://'), only the hostname and an explicit port, if set, (e.g. 'www.example.com:8080').
Parsing with the library doesn't seem to work when the scheme is missing:

With the scheme manually added ('http://' in this example), parsing results in expected correct Array:
````
$url = 'http://' . $_SERVER['HTTP_HOST'];
$uri_components = Uri\parse($url);
print_r($uri_components);
````

## Standalone code, or other way to reproduce the problem
````
$url = $_SERVER['HTTP_HOST']; // = 'www.example.com:8080';
$uri_components = Uri\parse($url);
print_r($uri_components);
````

### Expected result
````
Array ( [scheme] => http [user] => [pass] => [host] => www.example.com [port] => 8080 [path] => [query] => [fragment] => ) 
````

### Actual result
````
Array ( [scheme] => www.example.com [user] => [pass] => [host] => [port] => [path] => 8080 [query] => [fragment] => ) 
````

**Comment by nyamsprod** [comment]
The library parses URI in your example your are not providing a URI just a part of it. I believe what you really need is to use the Uri\create function instead. Please check the documentation for more details

**Comment by nyamsprod** [comment]
Or simply use the URI::createFromServer method in any case this is handle by the library but with some other part not Uri\parse

**Comment by strarsis** [comment]
@nyamsprod:
The static createFromServer method can't be find albeit Uri has been used:
`Fatal error: Uncaught Error: Class 'League\Uri'`
```php
use League\Uri;
$url = Uri::createFromServer($_SERVER);
````

**Comment by nyamsprod** [comment]
Sorry League\Uri\Http please read the documentation website for correct informations  I'm responding from my mobile 😉

**Comment by strarsis** [comment]
Thanks for your answer.
It works with `Http`, here is what I used:
```php
use League\Uri;
$url = Uri\Http::createFromServer($_SERVER);
````
