### ISSUE TITLE
Parsing is quite slow

### ISSUE THREAD

**Issue by kelunik** [thephpleague/uri#112]
## Issue summary

We have [migrated from our own `amphp/uri` to `league/uri` in the `0.8.x`](https://github.com/amphp/aerys/commit/9e9a87db0db77b7bddf79dc15f23bcef62ea8a02) development branch of Aerys, because we don't want to maintain our own library.

Unfortunately, we're seeing quite some slowdown. Previous to the linked commit, I was able to handle 14.4k requests per second on my notebook, with `league/uri` it's just about 10k.

This is just a hello world benchmark, but it's a pretty significant slowdown.

Related PRs:
 - https://github.com/thephpleague/uri-schemes/pull/6
 - https://github.com/thephpleague/uri-parser/pull/11
 - https://github.com/thephpleague/uri-parser/pull/12

## Standalone code, or other way to reproduce the problem

A benchmark is provided in https://github.com/thephpleague/uri-schemes/pull/6.

**Comment by nyamsprod** [comment]
version 5.3 is released with all the improve performance from the new uri-parser and uri-schemes. I'll close this one as resolved for now knowing that some improvement can still be added once we focused on the next major release for each package independently.
