### ISSUE TITLE
sameValueAs used in 5.0 documentation of Path Component, method no longer exists.

### ISSUE THREAD

**Issue by Zegnat** [thephpleague/uri#115]
The version 5.0 documentation for [Removing dot segments](https://github.com/thephpleague/uri/blob/065272e4020bc5d29692bc0238a26fba42f8b466/docs/5.0/components/path.md#removing-dot-segments) and [Removing empty segments](https://github.com/thephpleague/uri/blob/065272e4020bc5d29692bc0238a26fba42f8b466/docs/5.0/components/path.md#removing-empty-segments) uses `sameValueAs`. This method was deprecated in a version 4 release and never made it into a version 5 release, as far as I know.

**Comment by nyamsprod** [comment]
@Zegnat thanks for the report could you make a PR with the correction please ? thanks in advance
