### ISSUE TITLE
What happened to easy query params manipulation?

### ISSUE THREAD

**Issue by teohhanhui** [thephpleague/uri#116]
## Issue summary

The equivalent of:

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/append
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/set

I notice that it's really cumbersome to set / append query params now:

```php
$uri = $uri->withQuery((string) (new Query($uri->getQuery()))->append((string) Query::createFromPairs([
    'temp_url_sig' => $hash,
    'temp_url_expires' => $expires->getTimestamp(),
    'inline' => null,
])));
```

Is there an easier way that I can't find? The docs might need to be reorganized if that's the case.

**Comment by nyamsprod** [comment]
I depend on the version you are using from your example I'm guessing your using the develop vranch. If so you can use the functions defined in the `src/functions.php` most of these functions are already defined and documented on the documentation website. The API are still the same even though the implementation has drastically changed. Fwiw the dev package documentation is not yet written.

**Comment by teohhanhui** [comment]
It's `5.0`

**Comment by nyamsprod** [comment]
Then you can use the `uri-manipulations` package which is bundle with the URI package as described in the documentation. The functions are already present then

**Comment by nyamsprod** [comment]
you should be able to do this with the current stable release:

```php
use League\Uri;

$uri = Uri\append_query($uri, (string) Query::createFromPairs([
    'temp_url_sig' => $hash,
    'temp_url_expires' => $expires->getTimestamp(),
    'inline' => null,
]));
```

**Comment by teohhanhui** [comment]
It's still not as easy as it should be. I think it's reasonable to benchmark against the WhatWG URL.

**Comment by nyamsprod** [comment]
well ... this is being review in the v2 develop branch 👍  https://github.com/thephpleague/uri-components/issues/16  the implementation is done 90% still have issue around the new `Query::merge` method

**Comment by teohhanhui** [comment]
Thank you. I'll follow that.

**Comment by nyamsprod** [comment]
> It's still not as easy as it should be. 

What's not easy ? the public API or the function usage ?

**Comment by teohhanhui** [comment]
Imagine if I could do something like this:

```php
$uri->withQueryComponent($uri->getQueryComponent()->withPairs([
    'temp_url_sig' => $hash,
    'temp_url_expires' => $expires->getTimestamp(),
    'inline' => null,
]));
```

**Comment by teohhanhui** [comment]
Well, it's not so bad too, but perhaps it doesn't flow so nicely...

```php
<?php

$uri = (new AppendQuery((string) Query::createFromPairs([
    'temp_url_sig' => $hash,
    'temp_url_expires' => $expires->getTimestamp(),
    'inline' => null,
])))->process($uri);
```

**Comment by nyamsprod** [comment]
@teohhanhui the reason I'm using two objects is because of decoupling. you should be able to use the Uri class without the Query component and the other way around. Coupling both leads to less flexibility IMHO. As for the `AppendQuery` class. I now prefer using the function version as it is easier to use. If you need more flexibility then use the `Query` object directly. It's a balance between usability and flexibility.
