### ISSUE TITLE
Uri doesn't explicitly implement PSR-7 UriInterface

### ISSUE THREAD

**Issue by DaveRandom** [thephpleague/uri#117]
## Issue summary

I feel like I'm missing something obvious here, but the `League\Uri\Uri` class doesn't seem to implement the PSR-7 `UriInterface`? I cannot see any differences between the interface and the method signatures defined by the class (both `League\Uri\Interfaces\Uri` and `League\Uri\UriInterface` appear to be identical to (but not inherited from) the PSR interface?) but the `Uri` class itself doesn't implement that interface, and thus cannot be passed directly into an API that uses the PSR interface as a type declaration.

The `Http` variant implements it directly, but my use case involves arbitrary schemes and I cannot see any technical reason, nor any limitation in the PSR-7 spec, that would prevent this.

### System information

N/A

## Standalone code, or other way to reproduce the problem

```php
function foo(\Psr\Http\Message\UriInterface $uri) { }

$uri = \League\Uri\Uri::createFromString('scheme://whatever/stuff?and#things');
foo($uri); // TypeError
```

### Expected result

`Uri`s instantiated directly can be used with code that use `Psr\Http\Message\UriInterface` at the API boundary

### Actual result

The types are incompatible

---

Like I say I feel like I must be missing something obvious here, and there is a simple solution to this that I cannot see for looking.

**Comment by nyamsprod** [comment]
@DaveRandom Indeed both interfaces share the same signature but not the same wording around them which is why there is two interfaces. PSR-7 requires any implementation to supports the HTTP(s) scheme while the `League\Uri\UriInterface` does not. For instance `League\Uri\Data` which implements the Data URI specification does not supports the HTTP(s). Using the PSR-7 UriInterface in this case would be wrong.

**Comment by DaveRandom** [comment]
OK that seems reasonable, however does not seem to preclude the concrete `League\Uri\Uri` class from implementing the PSR-7 interface, as it has no such limitation.

As all the scheme-specific subclasses extend from `AbstractUri`, I can't *see* a conflict in allowing `Uri` to implement the PSR interface, although there may be some subtlety I have missed.

**Comment by nyamsprod** [comment]
yes it does ... because `League\Uri\Uri` only implements RFC3986 requirements and that's it.

- `League\Uri\Uri` accepts `http:example.org` as a legit URI 
- `League\Uri\Http` will throw given `http:example.org` because it's an invalid HTTP URI 

see the nuance ?

FWIW in the develop branch I made it more clear by removing `League\Uri\AbstractUr`i and having only the `League\Uri\Uri` class as basis for all other URI scheme specific classes.

**Comment by DaveRandom** [comment]
I actually don't see any restriction in the specification of PSR-7 `UriInterface` which states that it must always contain all the the necessary components for a HTTP URI, rather it states that:

> This interface is meant to represent URIs according to RFC 3986

and

> Its primary use is for HTTP requests, but may also be used in other contexts

**Comment by nyamsprod** [comment]
you have this

> The effective URL is represented by UriInterface. UriInterface models HTTP and HTTPS URIs as specified in RFC 3986 (the primary use case). The interface provides methods for interacting with the various URI parts, which will obviate the need for repeated parsing of the URI. It also specifies a __toString()
method for casting the modeled URI to its string representation.

And in the `UriInterface` docblock also this:

```php
    /**
     * Return an instance with the specified scheme.
     *
     * This method MUST retain the state of the current instance, and return
     * an instance that contains the specified scheme.
     *
     * Implementations MUST support the schemes "http" and "https" case
     * insensitively, and MAY accommodate other schemes if required.
     *
     * An empty scheme is equivalent to removing the scheme.
     *
     * @param string $scheme The scheme to use with the new instance.
     * @return static A new instance with the specified scheme.
     * @throws \InvalidArgumentException for invalid schemes.
     * @throws \InvalidArgumentException for unsupported schemes.
     */
    public function withScheme($scheme);
```

**Comment by nyamsprod** [comment]
That the reason my interface is in a separate repo https://github.com/thephpleague/uri-interfaces so you are not force to use my own implementations. That a start... Apart from that I know there use to be talk about a PSR around the URI itself but talk have stalled last time I check the PHP-FIG usergroup

**Comment by DaveRandom** [comment]
Thanks for your help, and thanks for your work on this lib... I guess I'll have to settle for docblock-based types for now, at least for input values :-/
