### ISSUE TITLE
Code improvements are possible

### ISSUE THREAD

**Issue by pawelkg** [thephpleague/uri#131]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| BC Break    | no

#### Proposal

There is a lack of some DocBlock in code, few methods are nearly same (so should united) and some methods should be simplified as Scrutinizer suggest.

**Comment by nyamsprod** [comment]
> some methods should be simplified as Scrutinizer suggest.

I use to follow Scrutinizer rules but nowadays I prefer static analysis like PHPStan to improve the code. They give better result. Also Some scrutinizer hint are not always accurate.

**Comment by nyamsprod** [comment]
The UriString and the Uri class should not be coupled while both class seems to perform the same set of operations their are not coupled per se for instance nothing prevents you to do the following

```php
<?php

$uri = Uri::createFromComponents(parse_url('http://example.com'));
```

The result of this operation should not depend in anyway or form on what or how UriString behave. The reason behind this is simple. If and when PHP fixes parse_url or introduces a new way of parsing the URL we may be able to refactor the Uri class and/or the UriString class too. By coupling them like you want to you reduce the ability for the library to evolve without resulting in multiple BC breaks.

Traits or Abstract class may work but they introduced protected properties and methods and/or remove the usage of constants (Traits). And most of all even if both classes appears to be doing the same thing they are not intent in doing the same thing they complement each other so some code duplication is not that bad ... on the contrary. At least that my opinion.

**Comment by pawelkg** [comment]
OK. So according to Your comment I prepared another PR (#134) which close this issue I think.
