### ISSUE TITLE
Is 'Authority is the colon' test is well designed?

### ISSUE THREAD

**Issue by pawelkg** [thephpleague/uri#136]
|    Q        |   A
|------------ | ------
| Version     | 6.0.0

### Question

A test 'Authority is the colon' looks like this: ftp://:/p?q#f
Test assume that host will be empty string and port will be null.
Shouldn't this result with empty string in host and port? Part after '//' and before colon refers in my opinion to host and after colon and before '/' (path part) refers to port.

**Comment by nyamsprod** [comment]
@pawelkg yes this test is correct according to [RFC3896](https://tools.ietf.org/html/rfc3986#section-6.2.3)  an empty port is equivalent to `null`. What you are assuming is not what the RFC specification is dictating.
