### ISSUE TITLE
Checks for invalid (?) host

### ISSUE THREAD

**Issue by pawelkg** [thephpleague/uri#137]
|    Q        |   A
|------------ | ------
| Version     | 6.0.0

### Question

Shouldn't this calls throws exceptions:
```php
UriString::parse('http://-a-.com');
UriString::parse('http://-a.com');
UriString::parse('http://a-.com');
UriString::parse('http://.domain.com');
UriString::parse('http://.');
UriString::parse('http://..');
```

**Comment by nyamsprod** [comment]
@pawelkg   No they should not because a host according to [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.2.2) is not limited to domain but also can be an IP or a registered name
