### ISSUE TITLE
Normalize URI

### ISSUE THREAD

**Issue by pawelkg** [thephpleague/uri#138]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal

It will be nice to have option to get normalized URI. In eg.:

```
'https://żółw.pl' => 'https://xn--w-uga1v8h.pl',
'https://例如.中国' => 'https://xn--fsqu6v.xn--fiqs8s',
'http://مثال.إختبار' => 'http://xn--mgbh0fb.xn--kgbechtv',
'https://example.com/żółty' => 'https://example.com/%C5%BC%C3%B3%C5%82ty',
'https://example.com/test/../index.html' => 'https://example.com/index.html',
'https://example.com/test/./index.html' => 'https://example.com/test/index.html',
'https://example.com?q=Spaces should be encoded' => 'http://example.com?q=Spaces%20should%20be%20encoded',
'https://example.com/foo(bar)baz quux' => 'https://example.com/foo%28bar%29baz+quux'
```

Note: I'm not sure if spaces in query should be converted to %20 or +.

**Comment by nyamsprod** [comment]
@pawelkg you should [read the documentation](uri.thephpleague.com) where you will see two main packages. What you are suggesting is possible with the [uri-components](https://uri.thephpleague.com/components/2.0/) package modifier class or with the UriResolver class which is present in the current repository.
