### ISSUE TITLE
ext-intl actually required..?

### ISSUE THREAD

**Issue by tomgidden** [thephpleague/uri#141]
|    Q        |   A
|------------ | ------
| Version     | 6.0.0

### Question

The documentation for 6.0 includes:

> In order to handle IDN host you are required to install the intl extension otherwise an exception will be thrown when attempting to validate or format such host.

This _suggests_ that if the `intl` extension was _not_ installed (contrary to advice, of course), then it might still work if only non-IDN hosts are used.

However, with a trivial test on PHP 7.2 _without_ `intl`:
```
$x = \League\Uri\Uri::createFromString("http://foo.com/");
```
I get:
```
PHP Fatal error:  Uncaught Error: Undefined constant 'IDNA_ERROR_EMPTY_LABEL' in …/vendor/league/uri/src/Uri.php:626
```

Of course, the obvious solution is to install `intl`, which I will be doing.

So, does the documentation need clarifying to say that `intl` is required whether IDN hosts are used or not; or should the library be fixed to only fail with a thrown exception if an IDN host is passed (as suggested by the current documentation)?

**Comment by nyamsprod** [comment]
I need to check that first but I'd say that

>  The library should be fixed to only fail with a thrown exception if an IDN host is passed (as suggested by the current documentation)?

Maybe I'm overchecking the host part because checking host can somehow be more difficult than it appears. Thanks for the issue ;)

**Comment by nyamsprod** [comment]
@tomgidden the next release will contain the patch
