### ISSUE TITLE
Resolve relative uri behaves strange

### ISSUE THREAD

**Issue by jaapio** [thephpleague/uri#145]
| Information | Description |
|--------------|---------|
| Version | 6.0.1 |
| PHP version | php 7.2  |
| OS Platform |  linux |

I'm not 100% sure if this is a bug or this is done by purpose. But it seems that there is some strange behavior in resolving an uri to another. The code below fails. Note that adding `./` before `../` solves this issue. But I do not understand why this is happening.

```
        $this->assertEquals(
            'file:///project/src',
            (string) UriResolver::resolve(
                Uri::createFromString('../src'),
                Uri::createFromString('file:///project/config')
            )
        );
        $this->assertEquals(
            'file:///project/src',
            (string) UriResolver::resolve(
                Uri::createFromString('./../src'),
                Uri::createFromString('file:///project/config')
            )
        );
```

#### Expected result

`file:///project/src`
`file:///project/src`

#### Actual result

`file:///src`
`file:///project/src`

**Comment by nyamsprod** [comment]
@jaapio this is expected behavior according to RFC3986 please refer to it's documentation for full description of dot segment removal
