### ISSUE TITLE
Broken links in CHANGELOG.md

### ISSUE THREAD

**Issue by reedy** [thephpleague/uri#146]
Under https://github.com/thephpleague/uri/blob/master/CHANGELOG.md#500---2017-02-06

The following links are broken in CHANGELOG.md
"Migration guide" - https://github.com/thephpleague/uri/blob/master/docs/upgrading/5.0
"documentation for the new version" - https://github.com/thephpleague/uri/blob/master/docs/dev-master

**Comment by nyamsprod** [comment]
That's because the links used to work on the documentation website. Maybe we can adjust them through a PR ?
