### ISSUE TITLE
Re-instate .gitattributes

### ISSUE THREAD

**Issue by reedy** [thephpleague/uri#147]
In https://github.com/thephpleague/uri/commit/2daaa898a9952e7d33421909889c3f4c6130a8c6 "the library is now a metapackge" (though, I'm not 100% sure what that actually means due to https://github.com/thephpleague/uri/issues/146), numerous entries were removed from .gitattributes

However, https://github.com/web-auth/webauthn-framework/blob/v3.0/composer.json#L43 is requiring this package in a non dev environment, for usage in one of the files in a sub package https://github.com/web-auth/webauthn-framework/blob/v3.0/src/metadata-service/src/MetadataService.php#L109-L117

This means, including the package then adds a load of files to vendor that aren't really needed...

```
	new file:   league/uri/.php_cs
	new file:   league/uri/.scrutinizer.yml
	new file:   league/uri/LICENSE
	new file:   league/uri/benchmark/build.php
	new file:   league/uri/benchmark/http-create-from-components.php
	new file:   league/uri/benchmark/parse.php
	new file:   league/uri/composer.json
	new file:   league/uri/phpstan.src.neon
	new file:   league/uri/phpstan.tests.neon
	new file:   league/uri/phpunit.xml
	new file:   league/uri/src/Http.php
	new file:   league/uri/src/Uri.php
	new file:   league/uri/src/UriInfo.php
	new file:   league/uri/src/UriResolver.php
	new file:   league/uri/src/UriString.php
	new file:   league/uri/tests/DataTest.php
	new file:   league/uri/tests/FactoryTest.php
	new file:   league/uri/tests/FileTest.php
	new file:   league/uri/tests/FtpTest.php
	new file:   league/uri/tests/HttpTest.php
	new file:   league/uri/tests/RelativizerTest.php
	new file:   league/uri/tests/ResolverTest.php
	new file:   league/uri/tests/UriInfoTest.php
	new file:   league/uri/tests/UriStringTest.php
	new file:   league/uri/tests/UriTest.php
	new file:   league/uri/tests/WsTest.php
	new file:   league/uri/tests/data/hello-world.txt
	new file:   league/uri/tests/data/john-doe.vcf
	new file:   league/uri/tests/data/red-nose.gif
```

Can we re-instate the .gitattributes excludes for tests, dot files etc? IIRC, if you still require-dev include the package, you don't get the filtered output, so this shouldn't make any day to day actual difference for those that want all the other files

**Comment by nyamsprod** [comment]
@reedy Indeed we could re-instate on based on the one present in the [uri-component package](https://github.com/thephpleague/uri-components/blob/master/.gitattributes).
