### ISSUE TITLE
Correct @inheritdoc usage

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/uri#16]
Inline `{@inheritdoc}` is meant to be used with additional content. Unwrapped it inherits the entire parent docblock:

```php
/**
 * @inheritdoc
 */
```

I see a couple of places that should be corrected:

https://github.com/thephpleague/uri/blob/e6acce40306d96222a1b5a4648e6ee3b97cff40c/src/UriParser.php#L194
https://github.com/thephpleague/uri/blob/e6acce40306d96222a1b5a4648e6ee3b97cff40c/src/UriParser.php#L202

Among others.

**Comment by nyamsprod** [comment]
Yep that's a mistake a quick find/replace will do the trick :+1:
