### ISSUE TITLE
URL 'Origin' like in WHATWG spec

### ISSUE THREAD

**Issue by GlassGruber** [thephpleague/uri#163]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | yes/no

#### Proposal

Hey there, just as title, it could be useful to have something like `get_origin()` to return a string containing the ["origin"](https://url.spec.whatwg.org/#origin) of the URL. According to WHATWG spec this is made of the URL `scheme`, `host` and `port`.

For example
````php
use League\Uri\Http;
$uri = Http::createFromString('http://user:pass@sub.example.com:8080/p/a/t/h?query=string#hash');

echo $uri->get_origin();
# http://sub.example.com:8080
````

ps. Thanks a lot for your time and effort in this and all the other League libraries! :)

**Comment by nyamsprod** [comment]
@GlassGruber thanks for the kind words toward the league maintainers.

As for your request there are a couple of reasons why `origin` was left out the current objects:

- `origin` is specific as you mentioned of the WHATWG URL Living standard specification but the current library is only compliant with RFC3986/RFC3987 URL specification which does not contain the origin property.
- `origin` is poorly specified as it somehow leaves out certain schemes (ie file) and is only correctly defined for a small subset or URL (http(s),ftp, ws(s)).
- WHATWG URL always have an `origin` while `RFC3986` URI may not.

As you can see these were blockers for me to add the origin property to the `Uri` or the `Http` classes.

Having said that, I'm open in seeing the library providing a mechanism to returns the URL origin but using the `UriInfo` class instead ? 

What do you think

**Comment by GlassGruber** [comment]
What you say looks totally sensed to me! 
I thought as well that an out-of-spec feature was a bit off as a request, I totally overlooked the UriInfo class, and it looks indeed as a fine candidate for an extra feature.

Thank you for your answer and time!

**Comment by nyamsprod** [comment]
@GlassGruber I've created a PR with a first implementation tell me what you think about the result.

**Comment by GlassGruber** [comment]
Looks good indeed! 

Thank you for your time in this and the super rapid response for such a side feature!

**Comment by nyamsprod** [comment]
the feature is merged to master it will be released hopefully during this week
