### ISSUE TITLE
Uri throws syntax error with misleading message

### ISSUE THREAD

**Issue by ptomulik** [thephpleague/uri#167]
### Bug Report

An exception with misleading message is thrown from [Uri::assertValidState()](https://github.com/thephpleague/uri/blob/3097a3798435ea95ae364d18b7c0953aeefb853b/src/Uri.php#L1110).

| Information | Description |
|--------------|---------|
| Version | master |
| PHP version |  |
| OS Platform |  |

#### Summary

If Uri validation fails at [this line](https://github.com/thephpleague/uri/blob/3097a3798435ea95ae364d18b7c0953aeefb853b/src/Uri.php#L1136), the error message always refers to ``"data"`` scheme. I believe it should mention the actual scheme of the URI being validated.

#### Standalone code, or other way to reproduce the problem

```php
\League\Uri\Uri::createFromString('file://example.org:80/home/jsmith/foo.txt');
```

#### Expected result

```console
League/Uri/Exceptions/SyntaxError with message 'The uri `file://example.org:80/home/jsmith/foo.txt` is invalid for the file scheme'
```

#### Actual result

```console
League/Uri/Exceptions/SyntaxError with message 'The uri `file://example.org:80/home/jsmith/foo.txt` is invalid for the data scheme'
```

**Comment by nyamsprod** [comment]
The fixe will be part of the next release. I've already fixed it in a local branch.

**Comment by nyamsprod** [comment]
the fix has landed on the master branch this issue is resolved.
