### ISSUE TITLE
Uri object does not implement league/uri-interfaces' UriInterface

### ISSUE THREAD

**Issue by ChargemapHakan** [thephpleague/uri#168]
### Bug Report

Declaration of League\Uri\Uri::withScheme($scheme): League\Uri\Contracts\UriInterface must be compatible with League\Uri\Contracts\UriInterface::withScheme(?string $scheme): League\Uri\Contracts\UriInterface

| Information | Description |
|--------------|---------|
| Version |  6.2 |
| PHP version |  7.3 |
| OS Platform | OSX  |

#### Summary

String parameters of method withXXX() such as withScheme or withUser are not explicitely specified in league/uri concrete class as they are supposed to in the relative interface.

#### Standalone code, or other way to reproduce the problem

 Uri::createFromString('random valid URI')

#### Expected result

Should not throw a fatal error

#### Actual result

Throws a fatal error.

**Comment by ChargemapHakan** [comment]
Tried to push a branch with a fix but it seems I can't push to the repo. :(

**Comment by nyamsprod** [comment]
@ChargemapHakan this is not a bug but an expected behaviour in PHP please review https://blog.kelunik.com/2018/01/23/parameter-type-widening.html for more informations

**Comment by ChargemapHakan** [comment]
Hi ! Well sorry, somehow I ended up composer updating with PHP 7.3 and testing my code with php 7.1... Anyway, thanks for your quick reply and sorry for the useless bug report !
