### ISSUE TITLE
Accepting Invalid Character in Path/Query/Fragment

### ISSUE THREAD

**Issue by binotaliu** [thephpleague/uri#174]
### Bug Report

| Information | Description |
|--------------|---------|
| Version | 6.3.0 |
| PHP version | 7.4.8 |
| OS Platform | macOS 11 |

#### Summary

In some case user might input an unnormalised string that contains some invalid characters in path/query/fragment. With current behaviour, `UriString` throws an SyntaxError.

#### Standalone code, or other way to reproduce the problem

Consider following example:

```php
<?php
use League\Uri\UriString;

$uri = "https://www.example.com/?search=バナナ\x08";
UriString::parse($uri); // SyntaxError
```

If we did an urlencode on the query string before sending it to UriString:
```php
<?php
use League\Uri\UriString;

$uri = "https://www.example.com/?search=%E3%83%90%E3%83%8A%E3%83%8A%08"
UriString::parse($uri); // parsed without problem
```

With the same example, I have tested it on browsers (Safari/Firefox) with [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL). It simply removes these characters:

```javascript
const url = new URL('https://www.example.com/?search=バナナ\x08')
url.toString() // "https://www.example.com/?search=%E3%83%90%E3%83%8A%E3%83%8A"
```

If we did urlencode before passing to URL, the character remain as it:
```javascript
const url = new URL('https://www.example.com/?search=%E3%83%90%E3%83%8A%E3%83%8A%08')
url.toString() // "https://www.example.com/?search=%E3%83%90%E3%83%8A%E3%83%8A%08"
```

#### Expected result

`UriString` should allow these characters in path/query/fragment.

#### Actual result

throws an `SyntaxError`

**Comment by nyamsprod** [comment]
@binotaliu thanks for using the library. From what I understand your are trying to parse an URI which contains invalid characters as defined in RFC 3986 which results in the exception you are getting. I'm afraid there is no work around about this unless using your own solution encoding your query before. I would suggest using the uri-components library for that
