### ISSUE TITLE
Classical setters with chaining

### ISSUE THREAD

**Issue by sunnyphp** [thephpleague/uri#175]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal

Hello.

I would like to be able to use class like this:
```php
$uri
	->setScheme($parse->getScheme())
	->setHost($parse->getHost())
	->setPort($parse->getPort())
	->setUserInfo($parse->getUserInfo())
;
```

instead of this:
```php
$uri = $uri
	->withScheme($parse->getScheme())
	->withHost($parse->getHost())
	->withPort($parse->getPort())
	->withUserInfo($parse->getUserInfo())
;
```

What do you think about this?

Thanks.

#### Example

https://gist.github.com/sunnyphp/d706c00cf62652a11f692fb3d037172c

**Comment by nyamsprod** [comment]
@sunnyphp thanks for using the library. May I ask what would be the added value to do that?

**Comment by sunnyphp** [comment]
For me, this is convenience and obviousness of using library.

I would assume that using setters would be slightly faster than cloning (most likely negligible).

**Comment by nyamsprod** [comment]
In PHP cloning is cheap, and more importantly in the package URI object are designed as immutable object hence the use of withers. Immutable objects wither makes sure the object are always in valid state and reduces bugs.
