### ISSUE TITLE
League\Uri\Components\Host is missing

### ISSUE THREAD

**Issue by teyeheimans** [thephpleague/uri#176]
### Bug Report

On this page is explained how you can analyze a host:

https://github.com/thephpleague/uri/blob/master/docs/index.md

However, the class `League\Uri\Components\Host` does not exists in the latest version. 

Is this functionality completely lost in version 6?

**Comment by nyamsprod** [comment]
@teyeheimans you should look into the real documentation at https://uri.thephpleague.com/

**Comment by teyeheimans** [comment]
Thanks. I think it would be better to remove the outdated documentation from the repository to prevent confusion.
