### ISSUE TITLE
git url parser

### ISSUE THREAD

**Issue by alekciy** [thephpleague/uri#182]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal

Add support parse git url like git@github.com:thephpleague/uri.git -> shema = null, user = git, password = null, host = github.com, port = null, path = thephpleague/uri.git, query = null, fragment = null.

Same like https://www.npmjs.com/package/git-url-parse

**Comment by nyamsprod** [comment]
@alekciy thanks for using the library. Since Git URL like string do not follow RFC3896 It would be difficult for me to add them here directly but I would welcome a PR with this added functionality. If it meets the package requirements I will gladly add it to it 😉  .

**Comment by alekciy** [comment]
I have done some research. It's scp-like style URI. I will prepare a PR.

**Comment by nyamsprod** [comment]
I will close this issue while waiting for a PR for it.
