### ISSUE TITLE
IDNA conversion normalisation on all URI packages

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/uri#188]
While working on #186 on the URI and URI-component package to standardized IDNA conversion through out the URI packages I stumble on this behaviour

```php
UriString::parse('https://xn--3/yo');
// throws a SyntaxError with the following message 
// The host `xn--3` is invalid : a label starts with "xn--" but does not contain valid Punycode
```

The `xn--3` is a valid host but it can not be converted to IDNA thus the exception being thrown.

Question: Should this exception even be raised  ? While this host can not be converted to unicode should it even be ?

two possibilities: 

- We keep the strictness of the parsing as is and the exception is kept on all packages
- We relax the parser and this host is enabled but converting it to unicode will lead to the current exception being thrown where applicable

Whatever solution is chosen I would consider it as a bug fix and not a BC break.

@kelunik what do you think. TBH I would go with the second solution.

**Comment by kelunik** [comment]
@nyamsprod Do you have links to the relevant specs / RFCs? Is there a chance of such names being used or are they invalid according to all relevant specs, so erroring out early makes sense?

**Comment by nyamsprod** [comment]
@kelunik  I believe this should be the reference we need 🤔  https://www.ietf.org/rfc/rfc3490.html#section-4.2
see how processing is done. 

also there is this quote

> While all ACE labels begin with the ACE prefix, not all labels
   beginning with the ACE prefix are necessarily ACE labels.  Non-ACE
   labels that begin with the ACE prefix will confuse users and SHOULD
   NOT be allowed in DNS zones.

**Comment by nyamsprod** [comment]
So my current take is the following:

- `League\Uri\UriString` SHOULD NOT throw because as a parser it is not its responsibility to go into validation details
- `League\Uri\Uri` and `League\Uri\Components\Host` classes SHOULD NOT  throw because they deal with registerable names and those host may be valid outside the DNS Zones
- `League\Uri\Components\Domain` SHOULD  throw as it is geared toward domain names usage in URI.

**Comment by nyamsprod** [comment]
Just read again  https://www.ietf.org/rfc/rfc3490.html#section-4.2 and the following is also included.

> ToUnicode never fails.  If any step fails, then the original input sequence is returned immediately in that step.

So I think that even my last take is incorrect:

`League\Uri\Components\Domain` SHOULD  NOT throw also. Everytime a toUnicode process is used, in case of error, it should return the input value modulo its non-destructive normalization if needed. @kelunik @nicolas-grekas What do you think ?

**Comment by nicolas-grekas** [comment]
Makes sense yes!

**Comment by nyamsprod** [comment]
#186 is merge with the behaviour fix
