### ISSUE TITLE
Improve documentation SEO

### ISSUE THREAD

**Issue by colinodell** [thephpleague/uri#191]
#### Proposal

One of my colleagues was looking for a way to rebuild a URL using an array returned from `parse_url()`.  Everything he searched for kept suggesting to use the `http_build_url()` method from the `http` PECL extension.  Perhaps including some a mention of `http_build_url()` in the documentation, along with keywords that other devs might search for to solve this problem, could help them find this library?

**Comment by nyamsprod** [comment]
indeed good suggestion will try to look into it. Will keep you posted

**Comment by GwendolenLynch** [comment]
Is there a publicly accessible git repo for the documentation that we can help with?

**Comment by nyamsprod** [comment]
@GwendolenLynch thanks for asking and for helping if possible. All documentations for the library can be found under the docs folder in the master branch. just create a PR and I will gladly reviewbyoue futur contributions
