### ISSUE TITLE
The url inside the composer.json should be in their secure version?

### ISSUE THREAD

**Issue by S-Tian86** [thephpleague/uri#196]
Hi,

I think the urls should be written with http:// instead of http://.
https://github.com/thephpleague/uri/blob/c8dc5e3dad96b118e8724640b3d1b410c999b206/composer.json#L27
What do you think?
Regards

**Comment by nyamsprod** [comment]
@S-Tian86 nice catch a PR for this quick fix is welcomed 😉

**Comment by S-Tian86** [comment]
Sure, no problem.
Note: Credits to PhpStorm inspections.
