### ISSUE TITLE
Want to add the function of filling replacement templates in order.

### ISSUE THREAD

**Issue by yinbug** [thephpleague/uri#212]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal

Want to add the function of filling replacement templates in order. 
It is better to support `array`

for example
`
 sprintf( 'http://xx.com/{id}/look/{pid}', $id, $pid);
`

**Comment by nyamsprod** [comment]
@yinbug What would this feature do that is not yet covered by 

- [UriTemplate feature](https://uri.thephpleague.com/uri/6.0/uri-template/)
- [Uri component package](https://uri.thephpleague.com/components/2.0/modifiers/)

**Comment by yinbug** [comment]
The array of the official example is a key value pair. I want to leave out the key names and fill them in order.
This is just an idea of mine.

Official example:
`
<?php

use League\Uri\UriTemplate;

$template = 'https://example.com/hotels/{hotel}/bookings/{booking}';
$params = ['booking' => '42', 'hotel' => 'Rest & Relax'];

$uriTemplate = new UriTemplate($template);
$uri = $uriTemplate->expand($params);
// $uri is an League\Uri\Uri instance.

echo $uri, PHP_EOL;
`

Fill in order:
`
<?php

use League\Uri\UriTemplate;

$template = 'https://example.com/hotels/{hotel}/bookings/{booking}';
$params = [ '42',  'Rest & Relax'];

$uriTemplate = new UriTemplate($template);
$uri = $uriTemplate->expand($params);
`

**Comment by nyamsprod** [comment]
Still I fail to see the added value. Why can't you just fill in the names of the arguments ?

**Comment by yinbug** [comment]
Maybe I want to be lazy. I don't want to input so many parameters.
