### ISSUE TITLE
Unused locale variable.

### ISSUE THREAD

**Issue by Fleshgrinder** [thephpleague/uri#3]
```php
$convert = function ($carry, $char) {
    return $carry .= str_pad(decbin(ord($char)), 8, '0', STR_PAD_LEFT);
};
$res = array_reduce(str_split(unpack('A16', inet_pton($ipv6))[1]), $convert, '');
```
https://github.com/thephpleague/uri/blob/master/src/Components/HostIpTrait.php#L173

**Comment by nyamsprod** [comment]
Please provide more informations on the issue. This closure is used in array reduce and both argument $carry and $char are also used so I fail to see the problem

**Comment by Fleshgrinder** [comment]
You add and assign the result of the `str_pad` function call to `$carry`, which makes no sense at this point. You either wanted to do:

```php
function ($carry, $char) {
    return $carry . $char;
}
```

Or:
```php
function ($carry, $char) {
    return $char;
}
```

But definitely not:
```php
function ($carry, $char) {
    return $carry .= $char;
}
```

Because the assignment makes no sense at this point, since you are directly returning.

**Comment by nyamsprod** [comment]
bug fixed
