### ISSUE TITLE
Fragment::getUriComponent wrongly evaluate the component emptyness

### ISSUE THREAD

**Issue by dmaicher** [thephpleague/uri#31]
I have this uri ```http://www.test.com?foo=bar#0``` and want to merge/append this query string ```bar=foo```.

The result is ```http://www.test.com?foo=bar&bar=foo0``` which is obviously wrong.

It should be ```http://www.test.com?foo=bar&bar=foo#0```.

I did not check the code but most likely its because `0` evaluates to false? ;)

**Comment by nyamsprod** [comment]
@dmaicher thanks for reporting the bug. The bug was not on the MergeQuery modifier but on the Fragment component. A patch will be made available as soon as possible

**Comment by dmaicher** [comment]
Thanks for the fast reaction :+1:  :)

**Comment by nyamsprod** [comment]
This bug fix will be made available in the [next release](https://github.com/thephpleague/uri/blob/master/CHANGELOG.md)

**Comment by dmaicher** [comment]
:+1:

**Comment by nyamsprod** [comment]
version 4.1 is out with the fix included

**Comment by dmaicher** [comment]
:+1:  thx
