### ISSUE TITLE
Is it possible to avoid usage of ext-intl?

### ISSUE THREAD

**Issue by Nayjest** [thephpleague/uri#34]
thephpleague/uri starts to require ext-intl that is not bundled with PHP by default and absent on some  shared hostings.

Therefore my company was forced to change uri processing library in our projects :(

**Comment by nyamsprod** [comment]
`ext-intl` is required for [IDN support](https://en.wikipedia.org/wiki/Internationalized_domain_name). and for host validation. This extension should be present on any decent share hosts as this extension is really quite useful even for non URI related problem like transcoding and translation. You should convinced your company to re-evaluate this. Not for URI sake but even for other products or solutions IMHO.
