### ISSUE TITLE
Http::createFromServer works incorrectly on some environments, no support of HTTP_X_FORWARDED_*

### ISSUE THREAD

**Issue by Nayjest** [thephpleague/uri#41]
HTTP_X_FORWARDED_HOST &  HTTP_X_FORWARDED_PORT are used when there is a proxy (or multiple proxies) between the browser and server (load balancers, etc).

You can see how it reproduces on *heroku*: see  $_SERVER vars in my [phpinfo](http://view-components.herokuapp.com/index.php/web-server-test/php-info).

So it's incorrect to use $_SERVER[SERVER_PORT] and $_SERVER[SERVER_HOST] on such environments.

Example of app where bug reproduces:

I have pagination links generation based on current URL [here](http://view-components.herokuapp.com/index.php/demo4_3).

Http::createFromServer generates links like http://view-components.herokuapp.com:47738/index.php/demo4_3 and they are broken because correct port value is 80

**Comment by Nayjest** [comment]
Please see my pull request https://github.com/thephpleague/uri/pull/42 that fixes this issue.

**Comment by nyamsprod** [comment]
Hi, thanks for using the library, as explained in the documentation there's a reason as to why [HTTP_X_* keys are not supported by the library](http://uri.thephpleague.com/uri/schemes/http/#instantiation). It's a matter of security as those header can easily be corrupted by the user.

**Comment by nyamsprod** [comment]
Having said that I would encourage you to use an [URI Modifier](http://uri.thephpleague.com/uri/manipulation/#uri-modifiers) to solve your issue something along the line of the following code:

```php
League\Uri\Schemes\Http as HttpUri;

$trustedProxies = ['10.0.0.1', '10.0.12.63', ...];

$modifier = new Example\ProxyModifier($trustedProxies, $_SERVER);
$uri = $modifier->__invoke(HttpUri::createFromServer($_SERVER));

//Where Example\ProxyModifier is an URI modifier 
```

You can look at how I implement [URI modifier](https://github.com/thephpleague/uri/blob/master/src/Modifiers/) to get a better idea

**Comment by Nayjest** [comment]
Nope, thanks, that's extremely overcomplicated solution.
