### ISSUE TITLE
Trait import somewhere in the middle of a class.

### ISSUE THREAD

**Issue by Fleshgrinder** [thephpleague/uri#5]
I know that PSR-2 does not define where trait uses should go. I just wanted to let you know that it is highly confusing if traits are imported somewhere in the middle of a class; one would not find it without an IDE. Consider to place the imports always at the same spot, which is in my opinion directly after the opening class brace.

**Comment by nyamsprod** [comment]
Mmh... I understand your concern but here's how I structure my class:
 
- const
- properties
- traits
- methods

Are you suggesting this order instead ?

- traits
- const
- properties
- methods

**Comment by nyamsprod** [comment]
I've change the order to:
- traits
- const
- properties
- methods
In the last commit

**Comment by Fleshgrinder** [comment]
That is exactly what I proposed. The rational behind this is simple, keep all uses together. Before the class declaration you find the imported classes and directly after the imported traits. This allows us to directly see all dependencies. :+1:

**Comment by Fleshgrinder** [comment]
Oh, yet another thing about your traits. You should not comment them. Why? Because the documentation for a structural element belongs to the structural element.

**Comment by nyamsprod** [comment]
no problem I'll remove the comments on the commit :+1:
