### ISSUE TITLE
Classes implementing interface methods without implementing interface …

### ISSUE THREAD

**Issue by Fleshgrinder** [thephpleague/uri#6]
There is a lot of weirdness going on in your code with classes that provide an interface without implementing an interface. This also destroys any automated code inspection, inversion of control, `instanceof` checks, and is highly confusing. All chains should always be complete and every class should only be coded against the interfaces. Additionally consider to suffix interfaces with `Interface` to avoid naming collisions.

**Comment by nyamsprod** [comment]
Again I need a concrete example As I am sure all components implements there respective interfaces correctly. I did not use the `ìnterface` suffix as all interfaces are already in a sub-namespace called `Interfaces`... It would make the name redundant IMHO

**Comment by nyamsprod** [comment]
I think by implementing issue #7 you'll see that the code is no so much confusing as you describe.

**Comment by Fleshgrinder** [comment]
Yeah, looks good. I might reopen at a later point but for now I consider this resolved. :+1:

**Comment by Fleshgrinder** [comment]
> I did not use the `ìnterface` suffix as all interfaces are already in a sub-namespace called `Interfaces`... It would make the name redundant IMHO

This is a PSR-2 violation btw. and “The League of PHP” makes the following statement “_We comply to the standards of the PHP-FIG_,” where PSR-2 is core value two. I suggest using a PSR-2 tool to check your code.

**Comment by philsturgeon** [comment]
@Fleshgrinder PSR-2 says nothing of the sort.

Please re-read: http://www.php-fig.org/psr/psr-2/

**Comment by Fleshgrinder** [comment]
Damn, you're right, I confused it with Symfony conventions. :yum:
