### ISSUE TITLE
UriParser should return false or throw a InvalidArgumentException like parse_url

### ISSUE THREAD

**Issue by prisis** [thephpleague/uri#63]
Hey :),

i think that this is a feature. But it would be nice if the UriParser can throw false or InvalidArgumentException on a invalid url like parse_url do.

**Comment by nyamsprod** [comment]
Well `UriParser` already throw an [InvalidArgumentException](https://github.com/thephpleague/uri/blob/master/test/UriParserTest.php#L384) if the submitted URI is not well formed. but do keep in mind that UriParser is **only a parser you should validate your URI using your constructor**. Here's a quote from the documentation:

> The UriParser class only parse and extract from the URI string its components. You still need to validate them against its scheme specific rules.
