### ISSUE TITLE
BC break: Splitting the package into 3 separate packages to ease maintenance

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/uri#65]
In version 4.0 the URI modifiers are tied to the URI package. To improve the URI package maintenance the Modifiers will be moved to their own package. 
The Modifiers will still require the main URI package **but** the main URI package will not require the modifier package.

**Comment by nyamsprod** [comment]
Here is the re-structuration I'm proposing for the next major release. Hope this will help maintaining the code more easily.

- `uri-components`: 

This package will contain all URI components and their respective Interface as well as the `QueryParser` class. The only external dependency will be with jeremykendall package domain parser. Technically speaking this is the **core** package as the two other packages will depend on it. I'll suggest install the other two packages in its composer manifest. The namespace prefix will be `League\Uri\Components`

- `uri`:

This is a stripped down version of the current package. The package will include the URI objects, the generic UriInterface as well as the RFC3986 compliant parser. The namespace prefix will be `League\Uri\Schemes`. It will require:
    - The `uri-components` package to create the URI objects.

- `uri-manipulation`:

This package aimed at easing manipulating URI objects that are either implementing the PSR-7 UriInterface class of the more generic `League\Uri\Schemes\Uri`. It will require :
    - The `uri` package to get access to the generic UriInterface.
    - The Psr-7 Interface package to get access the PSR-7 UriInterface
    - The `uri-components` package to enable manipulating URI parts.

**Because it will require the `uri` package il will provide a PSR-7 UriInterface implementation but is will never be bound to this specific implementation.**

To gain the v4 capability one will have to install all the packages.  

In closing the was an alternative which was to create 4 packages with the 4th package being composed of Interfaces only to avoid `uri-manipulation` to require the `uri` package completely.

Thoughts, remarks are welcomed

**Comment by shadowhand** [comment]
Rather than requiring users to install all of the packages separately, why not make `uri` a meta-package that requires all dependencies? That way end users don't need to make significant changes to their composer configuration. In essence:

`league/uri` requires:
- `league/uri-components`
- `league/uri-parser`
- `league/uri-maniuplation`

**Comment by nyamsprod** [comment]
@shadowhand I like this idea but rather that `league/uri-parser` I would call it `league/uri-schemes` but that's me nitpicking.

**Comment by shadowhand** [comment]
@nyamsprod that makes sense. Naming things is hard and I'm not _that_ familiar with the package.

**Comment by nyamsprod** [comment]
The package is split into these following sub package:
- [league uri interfarces](https://github.com/thephpleague/uri-interfaces)
- [league uri parser](https://github.com/thephpleague/uri-parser)
- [league uri components](https://github.com/thephpleague/uri-components)
- [league uri schemes](https://github.com/thephpleague/uri-schemes)
- [league uri manipulations](https://github.com/thephpleague/uri-manipulations)

Once each package are stabilized will we release league\Uri as a meta package 👍 to reduce BC break.
