### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by dantleech** [thephpleague/uri#75]
## Issue summary

The URI object is *much* slower than creating a "dumb" value object:

https://gist.github.com/dantleech/09547d9ecd145bb84c1b2e23e36a139c

Eagerly processing the URI causes unnecessary overhead (and might even be avoided if the user only requests the path?). Maybe it would be better to make the Uri object process lazily?

This could become an issue when creating many Uri objects in a single request.

**Comment by nyamsprod** [comment]
> The URI object is much slower than creating a "dumb" value object:

Your baseline is not a real value object it's just an object on which you've attach a string. An Uri is not simply a string it needs to be validated. The earlier, the better. 

Maybe you could make the same bench with other URI object to have a better view. I've created this package sometimes ago maybe it needs improvement. I know there are room for improvement but the validation state should stay IMHO.

https://github.com/nyamsprod/uri-parser-benchmarks

**Comment by dantleech** [comment]
> Your baseline is not a real value object it's just an object on which you've attach a string.

Yeah I know. Just wanted to "emulate" something like a lazy URI object.

> Maybe you could make the same bench with other URI object 

I created https://github.com/phpbench/uri-benchmarks (sorry for not contributing to yours, I wrote PHPBench so its good to actually use it sometimes :P).

It tests instantiating the object, and shows that this implementation is currently the slowest (not sure how fair some of them are, but I think ZendUri / Aura might be comparable).

**Comment by nyamsprod** [comment]
> I created https://github.com/phpbench/uri-benchmarks (sorry for not contributing to yours, I wrote PHPBench so its good to actually use it sometimes :P).

No problem. I'll look into it to see If I can make it more faster in v5. In v4 I was more interested in making it validate the URI correctly. As this was the main problem of League\Url its predecessor.

**Comment by nyamsprod** [comment]
I'll close this issue as it is being resolve in
- the [League Uri Parser package](https://github.com/thephpleague/uri-parser/issues/2)
- the [league Uri Schemes package](https://github.com/thephpleague/uri-schemes)
