### ISSUE TITLE
MergeQuery should support QueryInterface / __toString

### ISSUE THREAD

**Issue by teohhanhui** [thephpleague/uri#77]

**Comment by nyamsprod** [comment]
@teohhanhui `MergeQuery` does not support `QueryInterface::__toString` because `MergeQuery` should work with any query string not just the `QueryInterface` and since QueryInterface can be converted into a string there is no reason to add such possibility IMHO

**Comment by teohhanhui** [comment]
The point is that the casting / `__toString` can and should be automatically called.

Unless we're talking about `strict_types`, PHP is a loosely typed language and that would be the expected behaviour.

**Comment by nyamsprod** [comment]
By enforcing only a string type you:

- clearly define the expected type. 
- render your class strict mode independent
- make the class independent of the `QueryInterface` or of any object implementing the `__toString` method

I don't see the problem of simply doing this:

```php
<?php
$query = new Query('foo=bar&foo=baz');
$modifier  = new MergeQuery((string) $query);
```

**Comment by teohhanhui** [comment]
Okay, it's your call. Just saying this is not what most would expect when writing in PHP.

**Comment by nyamsprod** [comment]
@teohhanhui FWIW this is the exact behavior of [PSR-7 UriInterface](http://www.php-fig.org/psr/psr-7/#3-5-psr-http-message-uriinterface)

**Comment by teohhanhui** [comment]
> @teohhanhui FWIW this is the exact behavior of PSR-7 UriInterface

Do you mean this?

```php
/**
 * Return an instance with the specified query string.
 *
 * This method MUST retain the state of the current instance, and return
 * an instance that contains the specified query string.
 *
 * Users can provide both encoded and decoded query characters.
 * Implementations ensure the correct encoding as outlined in getQuery().
 *
 * An empty query string value is equivalent to removing the query string.
 *
 * @param string $query The query string to use with the new instance.
 * @return static A new instance with the specified query string.
 * @throws \InvalidArgumentException for invalid query strings.
 */
public function withQuery($query);
```

PHPDoc of `string` does not mean strict typing.

**Comment by nyamsprod** [comment]
@teohhanhui yes it does I had a long conversation while the PSR-7 was being put into review on this exact issue
