### ISSUE TITLE
Uri with backslash parsed differently than in browsers

### ISSUE THREAD

**Issue by kkopachev** [thephpleague/uri#79]
## Issue summary

Given uri `http://attacker.com\@www.host.com/`. League/uri parses that so host is `www.host.com` and `attacker.com\` is username part.
However, if that uri  opened in browser, backslash is converted to forward slash, which seems to be common behavior; happening in Chrome and FF.
I am not sure if this is in scope of this lib. I could not find anything helpful in RFC2396 and RFC3986.
### System informations

| Information | Description |
| --- | --- |
| League\Uri version | 4.1.1 |
| PHP/HHVM version | 5.6.*, 7.0 |
| OS Platform | Ubuntu/CentOS |
## Standalone code, or other way to reproduce the problem

``` php
$parsed = (new League\Uri\UriParser())->parse('http://attacker.com\@www.host.com/');
var_dump($parsed);
```
### _Possibly_ expected result

```
array(8) {
  'scheme' =>  string(4) "http"
  'user' =>  NULL
  'pass' =>  NULL
  'host' =>  string(12) "attacker.com"
  'port' =>  NULL
  'path' =>  string(14) "/@www.host.com"
  'query' =>  NULL
  'fragment' =>  NULL
}
```
### Actual result

```
array(8) {
  'scheme' =>  string(4) "http"
  'user' =>  string(13) "attacker.com\"
  'pass' =>  NULL
  'host' =>  string(12) "www.host.com"
  'port' =>  NULL
  'path' =>  string(1) "/"
  'query' =>  NULL
  'fragment' =>  NULL
}
```

Maybe uris with backslashes should throw exceptions as they are technically invalid? 
What do you think?

**Comment by nyamsprod** [comment]
Well I'd go with throwing an exception since the `\` character is invalid and the parser should not change the URI string.

**Comment by kkopachev** [comment]
@nyamsprod I am not sure about uris with `file:` scheme. Not sure if `\` is valid there.

**Comment by nyamsprod** [comment]
They are valid In Windows path but not in file scheme URI which are different specifications.

**Comment by nyamsprod** [comment]
@kkopachev 

Of note, in your report:

- Browsers handle more than URI, they also handle, for instance, filesystem paths. In this regard, browsers behavior do not always align with RFCs.
- Apart from the presence of the invalid character, the parser correctly parses the URI (according to RFC3986) so your *possibly* result is wrong.
- URI generate from this invalid URI is correctly encoded (on the master branch) meaning that

```php
<?php
use League\Uri\Schemes\Http as HttpUri;

echo HttpUri::createFromString('http://api.google.com\@toto.com/q?exp=a|b');
//displays 'http://api.google.com%5C@toto.com/q?exp=a%7Cb'
```

To correctly handle this bug I will have to make a BC break on how not only the parser works but also on how the components validates their respective component string. So correcting the bug in v4  implies a huge BC break that I'm not confortable with.
I would like to postpone the fix to the next major version where the BC break would be easier to implement and to document. What do you think ?

**Comment by kkopachev** [comment]
Hi @nyamsprod 

All bullet points you made seem valid and reasonable for me.
My use case is to prevent open redirect vulnerability, when redirect destination is passed as query parameter. So I am parsing `$_GET['destination']` to get host from the uri and then comparing such host with whitelist. 
For my problem I see couple options here. One would be to modify `$_GET['destination']` to be properly encoded; another - manually check uri for invalid characters and reject if found any. Currently I am using the last method. 

I am totally fine with fixing that in the next major release due to BC break. However implementation should check for other invalid characters in other parts of uri. Not quite sure what implications that might have. For example, would there be a method to get properly encoded uri if given invalid uri? How would one recover from such exception?

**Comment by nyamsprod** [comment]
@kkopachev exactly its because I wanted to take into account all invalid characters that it becomes a BC break.

**Comment by kkopachev** [comment]
Will there be an easy way to force-encode invalid characters rather then throw exception?

**Comment by nyamsprod** [comment]
> Will there be an easy way to force-encode invalid characters rather then throw exception?

What you are describing will be the default mode starting with version 4.2 and in accordance with PSR-7

> Users can provide both encoded and decoded path characters. Implementations ensure the correct encoding as outlined in getPath().

so yes in essence invalid character will be encoded. But this won't be the case with submitted URI using the `createFromString` named constructor. Because the parser will reject them prior to instantiation. You will have to use  `parse_url` combined with the `createFromComponents` named constructor but then you'll depend on PHP's `parse_url` which is full of bugs :)

**Comment by nyamsprod** [comment]
@kkopachev After some thinking this issue is similar to issue #85 . It may be badly documented but the *real* fact is that the Http class accepts URI and IRI as input but always returns URI in this regard what you observe is expected. And I believe this behavior will stay in the next release.

**Comment by nyamsprod** [comment]
This issue is resolve using the [league uri schemes](https://github.com/thephpleague/uri-schelmes/) repository and the [league uri manipulations](https://github.com/thephpleague/uri-manipulations/)

**Comment by sg2002** [comment]
Hello. I've read docs for both libraries and still don't understand how to use them to mitigate this problem. Can you give more info on the recommended flow here?

**Comment by nyamsprod** [comment]
@sg2002 Well the fact is that there's no issue per se. Both packages parse the URL according to RFC3986 while modern browsers uses the WHATG parsing algorithm. So there's no way to add this mitigation to the package. 

What you could do howerver is use the following package in PHP https://github.com/TRowbotham/URL-Parser
