### ISSUE TITLE
Problematic URL encoding for query string params with multiple values

### ISSUE THREAD

**Issue by mirfilip** [thephpleague/uri#81]
## Issue summary
The common way to pass multiple values under one query string parameter is the following:
`http://www.example.org?param[]=foo&param[]=bar`

When I store such URL in `Schemes\Http`, `[]` part of the query string undergoes normalization (RFC3986) and is url encoded. 
`[` -> `%5B`
`]` -> `%5D`
Is that expected?

### System informations

Irrelevant.

## Standalone code, or other way to reproduce the problem
```php
$uri = League\Uri\Schemes\Http::createFromString("http://www.example.org?param[]=foo&param[]=bar");
var_dump($uri);
```
### Expected result
```
class League\Uri\Schemes\Http#3 (1) {
  public $uri =>
  string(54) "http://www.example.org?param[]=foo&param[]=bar"
}
```
### Actual result
```
class League\Uri\Schemes\Http#3 (1) {
  public $uri =>
  string(54) "http://www.example.org?param%5B%5D=foo&param%5B%5D=bar"
}
```

**Comment by nyamsprod** [comment]
@mirfilip this is expected behavior  the `[, ]` characters are reserved characters  according to RFC3986 they must be encoded whenever you encounters them in a URI except for specific usage.

**Comment by mirfilip** [comment]
Fair enough @nyamsprod. Thx
