### ISSUE TITLE
MergeQuery returning wrong result

### ISSUE THREAD

**Issue by dmaicher** [thephpleague/uri#84]
## Issue summary

The `MergeQuery` modifier returns wrong result since update from `4.1.1` to `4.2.0`.
### System informations

| Information | Description |
| --- | --- |
| League\Uri version | 4.2.0 |
| PHP version | 5.6.22 |
| OS Platform | Debian 8 |
## Standalone code, or other way to reproduce the problem

``` php

use League\Uri\Modifiers\MergeQuery;
use League\Uri\Schemes\Http;

class UrlQueryStringAppender
{
    /**
     * @param string $url
     * @param array  $queryParams
     *
     * @return string
     */
    public function appendToUrl($url, array $queryParams)
    {
        if (count($queryParams) === 0) {
            return $url;
        }

        $uri = Http::createFromString($url);
        $modifier = new MergeQuery(http_build_query($queryParams));

        return $modifier->__invoke($uri)->__toString();
    }
}
```

``` php
(new UrlQueryStringAppender())->appendToUrl('http://localhost?foo=foo&bar=%26foo#bar', [
    'foo' => '%bar'
])
```
### Expected result

Should return `http://localhost?foo=%25bar&bar=%26foo#bar`
### Actual result

Now returns `http://localhost?foo=%BAr&bar=%26foo#bar`

Problem appears since I updated from 4.1.1 to 4.2.0.

**Comment by nyamsprod** [comment]
@dmaicher the bug is fixed on the master branch can you confirm it so I close this issue on the next release.

**Comment by dmaicher** [comment]
My test cases pass now :+1:

**Comment by nyamsprod** [comment]
version 4.2.1 is out which fixes this issue
