### ISSUE TITLE
Uri without end slash

### ISSUE THREAD

**Issue by ektarum** [thephpleague/uri#91]
## Issue summary
Uri without end slash throw error when call __invoke of AppendSegment.

The exemple code work without error in 4.1.1. The code crash when calling them in 4.2.*

I've not found BC break in changelog.

### System informations

| Information | Description |
|--------------|---------|
| League\Uri version | 4.2.1 |
| PHP/HHVM version |  5.6 |
| OS Platform |  unbuntu |

## Standalone code, or other way to reproduce the problem

```php5
<?php
namespace STS\PortailBundle\Service;

use League\Uri\Modifiers\AppendSegment;
use League\Uri\Schemes\Http as HttpUri;

// case 1
$uri = HttpUri::createFromString("http://www.example.com/report/");
$modifier = new AppendSegment('new-segment');
$uri = $modifier->__invoke($uri);
var_dump($uri);

// case 2
$uri = HttpUri::createFromString("http://www.example.com/report");
$modifier = new AppendSegment('new-segment');
$uri = $modifier->__invoke($uri);
var_dump($uri);

// case 3
$uri = HttpUri::createFromString("http://www.example.com/");
$modifier = new AppendSegment('new-segment');
$uri = $modifier->__invoke($uri);
var_dump($uri);

// case 4
$uri = HttpUri::createFromString("http://www.example.com");
$modifier = new AppendSegment('new-segment');
$uri = $modifier->__invoke($uri);
var_dump($uri);
```

### Expected result
case without end slash uri works

### Actual result
No problem when i'm create uri but call __invoke of AppendSegment with uri without end slash throw exception.

Is this a normal behavior?
Or my uri is not valid and the exception seems throw very late?

**Comment by nyamsprod** [comment]
@ektarum thanks for reporting this issue. A fix has been made. Could you test this on your code depending on your feedback a patch release will be released next week

**Comment by ektarum** [comment]
@nyamsprod thanks for reactivity, I just tested your patch in my real case, it works perfectly.

Thanks for all.

**Comment by nyamsprod** [comment]
version 4.2.2 is out with the fix

**Comment by ektarum** [comment]
All works fine !

Thanks for all !
