### ISSUE TITLE
Non breaking space UTF8 character is wiped in QueryParser

### ISSUE THREAD

**Issue by jaydiablo** [thephpleague/uri#94]
## Issue summary

As the title mentions, I ran into a specific UTF8 character (�, "%A0" when URL encoded), that when it's passed through the QueryParser component, it (and the entire string it's part of) gets wiped out completely.  I tested with other UTF8 characters, and those seem to be handled fine.  This particular character had given us some trouble in the past when passed through `htmlspecialchars` (php > 5.4) where it would exhibit the same behavior (the entire string containing the character would be wiped), which is why we have some tests against it.

I ran the same character (same array) through `http_build_query` and it gets urlencoded and turned into a query string just fine.

### System information

| Information | Description |
|--------------|---------|
| League\Uri version | 4.2.1 (latest) |
| PHP/HHVM version | PHP 5.6.28 & PHP 7.0.14 (same output) |
| OS Platform | Linux |

Both versions of PHP have the mbstring and intl extensions installed.

## Standalone code, or other way to reproduce the problem

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use League\Uri\QueryParser;

$params = [
    'goodutf8' => '神宮館abcdefg',
    // url decoding here because of past editor issues with this character
    'badutf8' => urldecode('%A0TM1TMS061114IP1'),
    'test' => 'true',
];

var_dump($params);

$queryParser = new QueryParser();
$queryString = $queryParser->build($params);

var_dump($queryString);

$queryString = http_build_query($params);

var_dump($queryString);
```

### Expected result

I'd expect both the `$queryParser->build()` command and the `http_build_query()` command to have the same output, but in the case of the `badutf` key they don't.  Here's the expected:

```
array(3) {
  'goodutf8' =>
  string(16) "神宮館abcdefg"
  'badutf8' =>
  string(16) "�TM1TMS061114IP1"
  'test' =>
  string(4) "true"
}
string(80) "goodutf8=%E7%A5%9E%E5%AE%AE%E9%A4%A8abcdefg&badutf8=%A0TM1TMS061114IP1&test=true"
string(80) "goodutf8=%E7%A5%9E%E5%AE%AE%E9%A4%A8abcdefg&badutf8=%A0TM1TMS061114IP1&test=true"
```

### Actual result

Here's the actual result, note that the `badutf` key is wiped entirely in the first dump (from QueryParser):

```
array(3) {
  'goodutf8' =>
  string(16) "神宮館abcdefg"
  'badutf8' =>
  string(16) "�TM1TMS061114IP1"
  'test' =>
  string(4) "true"
}
string(62) "goodutf8=%E7%A5%9E%E5%AE%AE%E9%A4%A8abcdefg&badutf8=&test=true"
string(80) "goodutf8=%E7%A5%9E%E5%AE%AE%E9%A4%A8abcdefg&badutf8=%A0TM1TMS061114IP1&test=true"
```

**Comment by nyamsprod** [comment]
@jaydiablo thanks for submitting this bug report. The fix was quite easy to make. Could you test it please so I can merge this to the master. Thanks in advance. Depending on #91 validation a patch version may be released next week

**Comment by jaydiablo** [comment]
👍Works perfectly (php 5.6 and 7.0), and I ran that branch against a larger suite of URL processing that we have and all tests pass.

Thanks!

**Comment by nyamsprod** [comment]
version 4.2.2 is out with the fix
