### ISSUE TITLE
How to get a path from absolute to relative?

### ISSUE THREAD

**Issue by shtse8** [thephpleague/uri#98]
I have two absolute paths and would like to get the relative path as follows:

$filePath = "/var/////www/static/../static/a.jpg";
$rootPath = "/var/./././www";

And I would like to get the relative path from $filePath and $rootPath:

$relativePath = ./static/a.jpg

How can I do this using this library?

I am moving from https://github.com/eloquent/pathogen to this.
here is my original code:
```
$filePath = "/var/////www/static/../static/a.jpg";
$rootPath = "/var/./././www";

$filePath = Path::fromString($filePath);
$rootPath = Path::fromString($rootPath);

$relativePath = $filePath->relativeTo($rootPath);
```

Reference: relativeTo https://github.com/eloquent/pathogen/blob/fbf5bbfced1cda81681acc708cb84557b0613ade/src/AbsolutePath.php#L170

**Comment by nyamsprod** [comment]
@shtse8 you can use URI middleware If I understand correctly your question see the [documentation website](http://uri.thephpleague.com/5.0/manipulations/middlewares/#middlewares-which-manipulate-several-uri-components) for that

**Comment by shtse8** [comment]
I have tried.

The code:
```

$filePath = "/var/././././www/static/../static/a.jpg";
$rootPath = "/var/./././www/";

$filePath = File::createFromString($filePath);
$rootPath = File::createFromString($rootPath);

$relativize = new Relativize($rootPath);
$relativePath = $relativize->process($filePath);

echo $relativePath, PHP_EOL;
```

Result:
```
.././www/static/../static/a.jpg
```

the `Relativize` seems not to normalize the path first.

**Comment by shtse8** [comment]
I also tried to normalize the paths before passing it to the `File::createFromString` as follow:

```
$filePath = "/var/////www/static/../static/a.jpg";
$rootPath = "/var/./././www";

$filePath = (new Path($filePath))->withoutDotSegments();
$rootPath = (new Path($rootPath))->withoutDotSegments();

$filePath = File::createFromString($filePath);
$rootPath = File::createFromString($rootPath);

$relativize = new Relativize($rootPath);
$relativePath = $relativize->process($filePath);

echo $relativePath, PHP_EOL;
```

Output:
```
PHP Fatal error:  Uncaught League\Uri\Schemes\UriException: Invalid URI: if there is no authority the path `%s` can not start with a `//` in /var/www/site/www/core/vendor/league/uri-schemes/src/AbstractUri.php:466
```

**Comment by nyamsprod** [comment]
It's because there is also an URI middleware for removing Dot segment `League\Uri\Modifiers\RemoveDotSegments`. It is also explained in the documentation

**Comment by shtse8** [comment]
I see. I am making a static file caching system. All my paths are `League\Uri\Components\HierarchicalPath`. But If I need to use `Relativize`, I have to convert all to Uri first. Should I use `Uri` instead of `Path`? But I need to modify the path anytime. and it seems `Uri` haven't any method to `append` or `prepend` the path or modifying the extension.

**Comment by shtse8** [comment]
I understand now. I should use Uri instead of Components. And then using middlewares to modify the Uri. Am I right? 
But it seems I have to code many lines to modify a path.
The Path component seems to be much easier.
```
$path = (new Path(CACHE_PATH))->append("css")->append("test.dd")->withExtension("css")->withoutEmptySegments();
```

**Comment by nyamsprod** [comment]
> I see. I am making a static file caching system. All my paths are League\Uri\Components\HierarchicalPath. But If I need to use Relativize, I have to convert all to Uri first. Should I use Uri instead of Path? But I need to modify the path anytime. and it seems Uri haven't any method to append or prepend the path or modifying the extension.

Why not create your own Middleware logic with the Pipeline URI middleware ? That would greatly help IMHO.

**Comment by shtse8** [comment]
@nyamsprod Thanks for your advice.

```
$path = "/var/////www/static/../static/a.jpg";
```

This path seems not to be valid and an exception is thrown.
```
PHP Fatal error:  Uncaught League\Uri\Schemes\UriException: Invalid URI: if there is no authority the path `%s` can not start with a `//` in /var/www/site/www/core/vendor/league/uri-schemes/src/AbstractUri.php:466
```

But I can use this path in linux.

**Comment by shtse8** [comment]
Also I cannot get the extension from the Uri.
```
use League\Uri\Schemes\File;
use League\Uri\Modifiers\Normalize;
use League\Uri\Modifiers\Relativize;
use League\Uri\Modifiers\AppendSegment;
use League\Uri\Modifiers\Extension;
use League\Uri\Modifiers\Pipeline;

$path = File::createFromString(CACHE_PATH);
$path = (new Pipeline())
	->pipe(new AppendSegment("css"))
	->pipe(new AppendSegment("test.dd"))
	->pipe(new Extension("css"))
	->pipe(new Normalize())
	->process($path);

echo $path->path->getExtension(), PHP_EOL;
```

output:
```
PHP Fatal error:  Uncaught BadMethodCallException: "path" is an undefined or inaccessible property in /var/www/site/www/core/vendor/league/uri-schemes/src/AbstractUri.php:1088
```
