### ISSUE TITLE
How can I get the extension from the FileUri

### ISSUE THREAD

**Issue by shtse8** [thephpleague/uri#99]
I cannot get the extension from the Uri.

```
use League\Uri\Schemes\File;
use League\Uri\Modifiers\Normalize;
use League\Uri\Modifiers\Relativize;
use League\Uri\Modifiers\AppendSegment;
use League\Uri\Modifiers\Extension;
use League\Uri\Modifiers\Pipeline;

$fileUri = File::createFromString(CACHE_PATH);
$fileUri = (new Pipeline())
	->pipe(new AppendSegment("css"))
	->pipe(new AppendSegment("filename"))
	->pipe(new Extension("css"))
	->pipe(new Normalize())
	->process($path);

echo $fileUri->path->getExtension(), PHP_EOL;
```

output:
```
PHP Fatal error:  Uncaught BadMethodCallException: "path" is an undefined or inaccessible property in /var/www/site/www/core/vendor/league/uri-schemes/src/AbstractUri.php:1088
```

**Comment by nyamsprod** [comment]
@shtse8 Please read the documentation where it is explained.

**Comment by shtse8** [comment]
@nyamsprod I have fully searched the document and found that the extension only can be got from `Path`. But not Uri.

**Comment by nyamsprod** [comment]
no the method is not missing you must use the `HierarchicalPath` class with the `Uri::getPath` method

**Comment by shtse8** [comment]
Accessing URI properties¶

All URI objects expose the same methods. You can access the URI string, its individual parts and components using their respective getter methods.

<?php

public Uri::__toString(): string
public Uri::getScheme(void): string
public Uri::getUserInfo(void): string
public Uri::getHost(void): string
public Uri::getPort(void): int|null
public Uri::getAuthority(void): string
public Uri::getPath(void): string
public Uri::getQuery(void): string
public Uri::getFragment(void): string
Which will lead to the following result for a simple HTTP URI:

<?php

use League\Uri\Schemes\Http;

$uri = Http::createFromString("http://foo:bar@www.example.com:81/how/are/you?foo=baz#title");
echo $uri;                 //displays "http://foo:bar@www.example.com:81/how/are/you?foo=baz#title"
echo $uri->getScheme();    //displays "http"
echo $uri->getUserInfo();  //displays "foo:bar"
echo $uri->getHost();      //displays "www.example.com"
echo $uri->getPort();      //displays 81 as an integer
echo $uri->getAuthority(); //displays "foo:bar@www.example.com:81"
echo $uri->getPath();      //displays "/how/are/you"
echo $uri->getQuery();     //displays "foo=baz"
echo $uri->getFragment();  //displays "title"

**Comment by shtse8** [comment]
But `Uri::getPath` returns a string instead of `HierarchicalPath` class. Does it mean I have to create a `HierarchicalPath` object using the string?
